### ISSUE TITLE
How would I use an URL from a previous step? 

### ISSUE THREAD

**Issue by NullVoxPopuli** [NiklasMerz/github-deployment-action#2]
I have my URL stored in a file, so I think that means it can be accessed in future steps?

**Comment by mickr** [comment]
It is a requirement I think for this plugin, because it writes the deployment id to a file in [on L12 of deployment.js](https://github.com/NiklasMerz/github-deployment-action/blob/master/deployment.js#L12)

**Comment by NiklasMerz** [comment]
I guess you could use shell syntax to get the url from the file:

```sh
action "set deployment status" {
  uses = "niklasmerz/github-deployment-action@master"
  needs = ["create deployment"]
  args = "-o niklasmerz -r myrepo -s success -u $(cat ./myfile) -f"
  secrets = ["GITHUB_TOKEN"]
}
```

I did not test this but this should work. Please try it and post results.

**Comment by NullVoxPopuli** [comment]
does that set the "Details" link to the file's content?

**Comment by NiklasMerz** [comment]
Yes it should do that if your file only contains the URL
