### ISSUE TITLE
"Top level 'run' is required for action.yml"

### ISSUE THREAD

**Issue by alstol** [NiklasMerz/github-deployment-action#5]
Hey @NiklasMerz, big fan of your work here :p. 

We noticed that the Action itself has stopped working after the last commit which added the `action.yml` file.
Here's the error that gets triggered:

`Download action repository 'niklasmerz/github-deployment-action@master'
##[error]Top level 'run:' section is required for /home/runner/work/_actions/niklasmerz/github-deployment-action/master/action.yml`

Just figured we'd let you know, cheers!

**Comment by ALibrada** [comment]
Hi @NiklasMerz thanks for your work ! 
I have the same problem, I will try to send a PR if I find the solution :)

**Comment by NiklasMerz** [comment]
Thanks for the kind words and reporting this issue. Github now requires actions to have action.yml. Documentation is here: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions#runs

I just pushed 512052545edcbb882afcc81cba0e72d5b016d13c . Please try the action from master. If that works, I can create a new version for the marketplace.

**Comment by alstol** [comment]
Seems to be working! 🚀 

Thanks!

**Comment by NiklasMerz** [comment]
Thanks for testing! A new version is released
